# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirstTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firstTest(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(1920, 1057)
    self.driver.find_element(By.NAME, "q").send_keys("Indonesia")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    elements = self.driver.find_elements(By.ID, "center_col")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Indonesia - Wikipedia"
  
